version: '3.1'

services:
  invites_app:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile.test
    image: invites_app
    environment:
      TESTING: 1
    networks:
      - app
    volumes:
      - ./alembic_migrations:/application/alembic_migrations/  # for dev only
    command: "pytest -s"

networks:
  app:
