#!/bin/env bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}' NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "DROP DATABASE IF EXISTS ${DATABASE_NAME};"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE DATABASE ${DATABASE_NAME} owner ${DATABASE_USER};"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" ${DATABASE_NAME} -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"";
